lessons:
  outputs:
    dev:
      dataset: dbt_udemy
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: fine-citadel-421114
      threads: 20
      type: bigquery
  target: dev
